name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker buildx build . --file Dockerfile --tag texlive-ja
      - name: Test the Docker image
        run: docker run -v $(pwd)/test:/workdir texlive-ja llmk
